// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DaefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNy1qeWToSPtdnV0lTQnICO1AeQhtFnqI',
    appId: '1:441133820232:web:dc1e4979d5ce04cd0eeb7d',
    messagingSenderId: '441133820232',
    projectId: 'theevent-a4e4c',
    authDomain: 'theevent-a4e4c.firebaseapp.com',
    storageBucket: 'theevent-a4e4c.firebasestorage.app',
    measurementId: 'G-4PQ8XWZSVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgphc_maWTT88kSBkHU8UGhLFaP1bKE4g',
    appId: '1:441133820232:android:b9575d69733d63dd0eeb7d',
    messagingSenderId: '441133820232',
    projectId: 'theevent-a4e4c',
    storageBucket: 'theevent-a4e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgTE-KlWcMh5lIHXJRZj3ipBWlSOaDpI',
    appId: '1:441133820232:ios:b3f4b838399a13e60eeb7d',
    messagingSenderId: '441133820232',
    projectId: 'theevent-a4e4c',
    storageBucket: 'theevent-a4e4c.firebasestorage.app',
    iosBundleId: 'com.example.alpDepd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgTE-KlWcMh5lIHXJRZj3ipBWlSOaDpI',
    appId: '1:441133820232:ios:b3f4b838399a13e60eeb7d',
    messagingSenderId: '441133820232',
    projectId: 'theevent-a4e4c',
    storageBucket: 'theevent-a4e4c.firebasestorage.app',
    iosBundleId: 'com.example.alpDepd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNy1qeWToSPtdnV0lTQnICO1AeQhtFnqI',
    appId: '1:441133820232:web:308caaf47b71cb470eeb7d',
    messagingSenderId: '441133820232',
    projectId: 'theevent-a4e4c',
    authDomain: 'theevent-a4e4c.firebaseapp.com',
    storageBucket: 'theevent-a4e4c.firebasestorage.app',
    measurementId: 'G-XSRJ620BZZ',
  );
}
